// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApiProject.Models;

#nullable disable

namespace MyApiProject.Migrations
{
    [DbContext(typeof(HastaneContext))]
    partial class HastaneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApiProject.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__Appointm__3214EC07039A92A5");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.AppointmentToDoktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentFk")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentFK");

                    b.Property<int>("DoktorFk")
                        .HasColumnType("int")
                        .HasColumnName("DoktorFK");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentFk");

                    b.HasIndex("DoktorFk");

                    b.ToTable("Appointment_To_Doktor", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("Userıd")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.ToTable("Audit Logs", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Alan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("RefreshTokenEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Tc")
                        .HasColumnType("bigint");

                    b.Property<string>("İsim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Doktor", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.Hastum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("RefreshTokenEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Tc")
                        .HasColumnType("bigint");

                    b.Property<string>("İsim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Hasta_1");

                    b.ToTable("Hasta");
                });

            modelBuilder.Entity("MyApiProject.Models.HospitalReceptionist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Alan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("RefreshTokenEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Tc")
                        .HasColumnType("bigint");

                    b.Property<string>("İsim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HospitalReceptionist", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.Ilac", b =>
                {
                    b.Property<int>("IlacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IlacID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlacId"));

                    b.Property<string>("IlacName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("Ilac_Name")
                        .IsFixedLength();

                    b.Property<string>("KullanımAlanı")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("Kullanım_Alanı")
                        .IsFixedLength();

                    b.HasKey("IlacId");

                    b.ToTable("Ilac", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.IlcaToRecete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("IlcaFk")
                        .HasColumnType("int")
                        .HasColumnName("IlcaFK");

                    b.Property<int>("ReceteFk")
                        .HasColumnType("int")
                        .HasColumnName("ReceteFK");

                    b.HasKey("Id");

                    b.HasIndex("IlcaFk");

                    b.HasIndex("ReceteFk");

                    b.ToTable("Ilca_To_Recete", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.Kayıt", b =>
                {
                    b.Property<int>("KayıtId")
                        .HasColumnType("int");

                    b.Property<int?>("RandevuFk")
                        .HasColumnType("int")
                        .HasColumnName("RandevuFK");

                    b.Property<string>("YönlendirmeFişi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("KayıtId");

                    b.HasIndex("RandevuFk");

                    b.ToTable("Kayıt", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.OnlineRandevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoktorId")
                        .HasColumnType("int")
                        .HasColumnName("DoktorID");

                    b.Property<string>("DoktorName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("DoktorSurname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<int>("HastaId")
                        .HasColumnType("int")
                        .HasColumnName("HastaID");

                    b.Property<string>("HastaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("HastaSurname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("HastaŞikayet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("Saat")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("HastaId");

                    b.ToTable("OnlineRandevu", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.Recete", b =>
                {
                    b.Property<int>("ReceteId")
                        .HasColumnType("int")
                        .HasColumnName("ReceteID");

                    b.Property<DateOnly>("GecerlilikTarihi")
                        .HasColumnType("date")
                        .HasColumnName("Gecerlilik_Tarihi");

                    b.Property<string>("Kullanım")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("ReceteId");

                    b.ToTable("Recete", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.Tedavi", b =>
                {
                    b.Property<int>("TedaviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TedaviID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TedaviId"));

                    b.Property<int>("DoktorId")
                        .HasColumnType("int")
                        .HasColumnName("DoktorID");

                    b.Property<int>("HastaId")
                        .HasColumnType("int")
                        .HasColumnName("HastaID");

                    b.Property<string>("Tanı")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("TedaviId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("HastaId");

                    b.ToTable("Tedavi", (string)null);
                });

            modelBuilder.Entity("MyApiProject.Models.AppointmentToDoktor", b =>
                {
                    b.HasOne("MyApiProject.Models.Appointment", "AppointmentFkNavigation")
                        .WithMany("AppointmentToDoktors")
                        .HasForeignKey("AppointmentFk")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_To_Doktor_Appointment");

                    b.HasOne("MyApiProject.Models.Doktor", "DoktorFkNavigation")
                        .WithMany("AppointmentToDoktors")
                        .HasForeignKey("DoktorFk")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_To_Doktor_Doktor");

                    b.Navigation("AppointmentFkNavigation");

                    b.Navigation("DoktorFkNavigation");
                });

            modelBuilder.Entity("MyApiProject.Models.IlcaToRecete", b =>
                {
                    b.HasOne("MyApiProject.Models.Ilac", "IlcaFkNavigation")
                        .WithMany("IlcaToRecetes")
                        .HasForeignKey("IlcaFk")
                        .IsRequired()
                        .HasConstraintName("FK_Ilca_To_Recete_Ilac");

                    b.HasOne("MyApiProject.Models.Recete", "ReceteFkNavigation")
                        .WithMany("IlcaToRecetes")
                        .HasForeignKey("ReceteFk")
                        .IsRequired()
                        .HasConstraintName("FK_Ilca_To_Recete_Recete");

                    b.Navigation("IlcaFkNavigation");

                    b.Navigation("ReceteFkNavigation");
                });

            modelBuilder.Entity("MyApiProject.Models.Kayıt", b =>
                {
                    b.HasOne("MyApiProject.Models.OnlineRandevu", "RandevuFkNavigation")
                        .WithMany("Kayıts")
                        .HasForeignKey("RandevuFk")
                        .HasConstraintName("FK_Kayıt_OnlineRandevu");

                    b.Navigation("RandevuFkNavigation");
                });

            modelBuilder.Entity("MyApiProject.Models.OnlineRandevu", b =>
                {
                    b.HasOne("MyApiProject.Models.Doktor", "Doktor")
                        .WithMany("OnlineRandevus")
                        .HasForeignKey("DoktorId")
                        .IsRequired()
                        .HasConstraintName("FK_OnlineRandevu_Doktor");

                    b.HasOne("MyApiProject.Models.Hastum", "Hasta")
                        .WithMany("OnlineRandevus")
                        .HasForeignKey("HastaId")
                        .IsRequired()
                        .HasConstraintName("FK_OnlineRandevu_Hasta1");

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("MyApiProject.Models.Recete", b =>
                {
                    b.HasOne("MyApiProject.Models.Tedavi", "ReceteNavigation")
                        .WithOne("Recete")
                        .HasForeignKey("MyApiProject.Models.Recete", "ReceteId")
                        .IsRequired()
                        .HasConstraintName("FK_Recete_Tedavi");

                    b.Navigation("ReceteNavigation");
                });

            modelBuilder.Entity("MyApiProject.Models.Tedavi", b =>
                {
                    b.HasOne("MyApiProject.Models.Doktor", "Doktor")
                        .WithMany("Tedavis")
                        .HasForeignKey("DoktorId")
                        .IsRequired()
                        .HasConstraintName("FK_Tedavi_Doktor");

                    b.HasOne("MyApiProject.Models.Hastum", "Hasta")
                        .WithMany("Tedavis")
                        .HasForeignKey("HastaId")
                        .IsRequired()
                        .HasConstraintName("FK_Tedavi_Hasta");

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("MyApiProject.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentToDoktors");
                });

            modelBuilder.Entity("MyApiProject.Models.Doktor", b =>
                {
                    b.Navigation("AppointmentToDoktors");

                    b.Navigation("OnlineRandevus");

                    b.Navigation("Tedavis");
                });

            modelBuilder.Entity("MyApiProject.Models.Hastum", b =>
                {
                    b.Navigation("OnlineRandevus");

                    b.Navigation("Tedavis");
                });

            modelBuilder.Entity("MyApiProject.Models.Ilac", b =>
                {
                    b.Navigation("IlcaToRecetes");
                });

            modelBuilder.Entity("MyApiProject.Models.OnlineRandevu", b =>
                {
                    b.Navigation("Kayıts");
                });

            modelBuilder.Entity("MyApiProject.Models.Recete", b =>
                {
                    b.Navigation("IlcaToRecetes");
                });

            modelBuilder.Entity("MyApiProject.Models.Tedavi", b =>
                {
                    b.Navigation("Recete");
                });
#pragma warning restore 612, 618
        }
    }
}
